apiVersion: v1
kind: Service
metadata:
  name: weather-data-app
  labels:
    app: weather-data-app
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: weather-data-app